name = "New Bootstrap Blog"
license = "GPL-3.0"
licenselink = "https://github.com/alanorth/hugo-theme-bootstrap4/blob/master/LICENSE.txt"
description = "A modified version of the Bootstrap v4 blog theme."
homepage = "https://github.com/abilenky/hugo-theme-bootstrap4-blog"
tags = ["bootstrap", "blog", "fontawesome"]
features = ["responsive", "blog"]
min_version = 0.18

[author]
  name = "Aaron Bilenky"
  homepage = "https://github.com/abilenky/hugo-theme-bootstrap4-blog"

[original]
  name = "Alan Orth"
  homepage = "https://englishbulgaria.net"

# vim: ts=2 sw=2 et
